### PR TITLE
[Fixes]: Invalid Input Sanitization #8

### PR DESCRIPTION
**Pull request by aryansharma220**
Fixes: #8 

Added error message and input sanitization. Will only allow to enter the valid input

https://github.com/adarsh-singh01/PrithWe/assets/133234867/e67fea67-152b-4afd-9210-8413d6533104

### CODE REVIEW

**Comment by adarsh-singh01** [comment]
> Fixes: #8 
> 
> Added error message and input sanitization. Will only allow to enter the valid input
> 
> https://github.com/adarsh-singh01/PrithWe/assets/133234867/e67fea67-152b-4afd-9210-8413d6533104
> 
> 

Have you made changes to the original UI?.

**Comment by aryansharma220** [comment]
> > Fixes: #8 
> > 
> > Added error message and input sanitization. Will only allow to enter the valid input
> > 
> > https://github.com/adarsh-singh01/PrithWe/assets/133234867/e67fea67-152b-4afd-9210-8413d6533104
> > 
> > 
> 
> Have you made changes to the original UI?. 

Yep just an idea if you like then we keep it else i can revert it just keeping the error message

**Comment by aryansharma220** [comment]
> > Fixes: #8 
> > 
> > Added error message and input sanitization. Will only allow to enter the valid input
> > 
> > https://github.com/adarsh-singh01/PrithWe/assets/133234867/e67fea67-152b-4afd-9210-8413d6533104
> > 
> > 
> 
> Have you made changes to the original UI?. 

No I haven't changed the UI, your UI is not loading properly because I removed some components to run the code on my remote computer. So the UI is the same as usual

**Comment by adarsh-singh01** [comment]
Hey Aryan,
Sorry for the late reply.

Can you please tell the components that were not loading properly or causing errors in your system, as we do want to delete any existing component and we need to keep our UI just as...it is now

**Comment by aryansharma220** [comment]
> Hey Aryan, Sorry for the late reply.
> 
> Can you please tell the components that were not loading properly or causing errors in your system, as we do want to delete any existing component and we need to keep our UI just as...it is now

@adarsh-singh01 There is no issue with the UI, I was saying that to open the page without logging In i had to remove some of the compoments, thats why the UI is not loading properly in the video I sent. The UI of the website is perfectly fine.

**Comment by adarsh-singh01** [comment]
hey this merge has caused changes in the UI of household form...fix that and send a PR

**Comment by adarsh-singh01** [comment]
> hey this merge has caused changes in the UI of household form...fix that and send a PR

Hello, the UI of the household form has changed. 

Kindly Fix that.

**Comment by aryansharma220** [comment]
> > hey this merge has caused changes in the UI of household form...fix that and send a PR
> 
> Hello, the UI of the household form has changed. 
> 
> Kindly Fix that. 

Hey @adarsh-singh01 I am out of town right now, i will get it done by tonight

**Comment by adarsh-singh01** [comment]
> > > hey this merge has caused changes in the UI of household form...fix that and send a PR
> > 
> > Hello, the UI of the household form has changed. 
> > 
> > Kindly Fix that. 
> 
> Hey @adarsh-singh01 I am out of town right now, i will get it done by tonight 

Okay

**Comment by adarsh-singh01** [comment]
Hey, the form is not being submitted and the font of error beneath the household inputs and business inputs are different...

**Comment by adarsh-singh01** [comment]
Hey, the form is not being submitted and the font of error beneath the household inputs and business inputs are different...

**Comment by adarsh-singh01** [comment]
I have assigned this issue to other contributor

**Pull request merged**
