### PR TITLE
Email Verification Added

### PR DESCRIPTION
**Pull request by SamarthUrane**
I have added Email Verification. Before user try to login System will check if it is verified or not and if not otp verification will be performed. I also updated readme accordingly

User will be redirected to verifyEmail page after register or if user is not verified
image

OTP will be sent to verify Email
image

### CODE REVIEW

**Comment by SamarthUrane** [comment]
Solved Issue #40 under GSSOC'24. Please check this and merge this

**Comment by adarsh-singh01** [comment]
This email "maileroereview@gmail.com" Will be sending the OTPs ? 

Can i change it with my account?

Kindly send a short clip of this functionality.

**Comment by SamarthUrane** [comment]
> This email "[maileroereview@gmail.com](mailto:maileroereview@gmail.com)" Will be sending the OTPs ?
> Can i change it with my account?
> Kindly send a short clip of this functionality.

> I have updated the code mail will be sent from the mail ID mentioned in .env file


https://github.com/adarsh-singh01/PrithWe/assets/108013711/e7daafed-04b3-42e9-a112-740255e260e4

**Comment by adarsh-singh01** [comment]
How does it know that the mail mentioned in the  .env is mine and not of somebody else. 

Don't I need to verify it to nodemailer? 

And why the UI looks little changed,the toast alert text is coming in half. 

Kindly reply ASAP.

**Comment by SamarthUrane** [comment]
Mail will be sent from mail id whose app password you have created in Google account.
This app password with its corresponding is provided to send mail.

I will look into UI part shortly

**Comment by adarsh-singh01** [comment]
Hey @SamarthUrane bro ,why did you closed this PR?

**Comment by SamarthUrane** [comment]
My old code was having too much conflict with main branch due to other merges. I will open a new PR with latest code

**Comment by adarsh-singh01** [comment]
Oh okay, 

Yes many changes had occurred today only ,  the repo you had forked should have become few commits behind. 

Try resolving the conflicts in the VS Code , it provides the merge editor which is easy to use.

**Pull request closed without merging**
