### PR TITLE
[Bug]: Incorrect padding of the website

### LINKED ISSUE #72: [Bug]: Incorrect padding of the website
**Description:**

The padding on the website is incorrect,which degrades the overall look of the website.

**Steps to Reproduce:**

- Go to the "PrithWe" website: https://prithwe.onrender.com/
- Notice the Incorrect Padding

**Expected Behaviour:**

- Padding should be `0` for the Navbar and Footer

**Screenshots:**

Screenshot (189)

**Additional Context:**

I am happy to contribute by fixing this bug myself. Please let me know if you have any feedback or additional requirements.

[X] I am a GSSOC'24 Contributor

Thank you for considering my request!

### PR DESCRIPTION
**Pull request by shreyash3087**
**Description:**

This PR fixes the padding of the entire website,which was causing problems in the overall look of the website.

**Issue Mentioned:**

- Fixes #72

**Changes Made:**

- Removed padding from the `#root` id in `App.css` .

**ScreenShots:**

screencapture-prithwe-543y-onrender-2024-06-04-07_05_31

**Additional Context:**

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@adarsh-singh01 You can merge this,its fixed.

**Review by adarsh-singh01 — CHANGES_REQUESTED** [review]
Remove the text align center also

**Comment by shreyash3087** [comment]
@adarsh-singh01 Done

**Comment by shreyash3087** [comment]
@adarsh-singh01 also please put the label and assignees on this one too

**Pull request merged**
