### PR TITLE
Added AI integration for recommendation

### PR DESCRIPTION
**Pull request by SamarthUrane**
Solved Issue No. #94
For Business Account
Screenshot 2024-06-07 190615

For Household Account
Screenshot 2024-06-07 160521

### CODE REVIEW

**Comment by SamarthUrane** [comment]
I have created a table to store recommendations and it is storing as expected. I will show this recommendation as discussed in admin dashboard and history page in another PR for #90

**Comment by SamarthUrane** [comment]
I have some other work so I will do the remaining task tomorrow or day after tomorrow

**Comment by adarsh-singh01** [comment]
> I have created a table to store recommendations and it is storing as expected. I will show this recommendation as discussed in admin dashboard and history page in another PR for #90

Okay

**Comment by adarsh-singh01** [comment]
> I have some other work so I will do the remaining task tomorrow or day after tomorrow

Okay okay, no problem

**Comment by adarsh-singh01** [comment]
> You haven't merge this PR is their is in problem In it?

Didn't get time to review... We'll merge it till 11.59pm

**Comment by adarsh-singh01** [comment]
might do it after 11.59pm...currently reviewing the code

**Comment by SamarthUrane** [comment]
No problem take your time

**Pull request merged**
