### PR TITLE
FEAT: - History page

### PR DESCRIPTION
**Pull request by Tomkndn**
Fixes - #9 
Description - Implemented history page where user can check history of their carbon footprints previously calculated with the Doughnut Chart.

### CODE REVIEW

**Comment by adarsh-singh01** [comment]
Kindly send a short video of this functionality.

**Comment by Tomkndn** [comment]
https://github.com/adarsh-singh01/PrithWe/assets/105445488/454fc161-ec7b-416d-9c7b-820289c9a347

**Comment by adarsh-singh01** [comment]
can you show the household common entries and just below them should be entries of associated family members that were entered at that time...and after that result&chart is shown

Screenshot 2024-06-06 012817




and business form is also saving the entries in the DB...make for that too.

**Comment by adarsh-singh01** [comment]
try to make it responsive

**Comment by adarsh-singh01** [comment]
hey i am adding one more contributor in this because he is working on a similar functionality.

**Comment by SamarthUrane** [comment]
Please add labels

**Comment by Tomkndn** [comment]
just check this

https://github.com/adarsh-singh01/PrithWe/assets/105445488/ed99fb84-8110-4359-8ccc-61ff82828c4a

**Comment by adarsh-singh01** [comment]
> just check this
> 
>  Screencast.from.2024-06-07.00-05-49.mp4

It is nice but i realised that it looks very Cluttered and covered with a lot of things.

i want that at first only few entries along with its date&time is shown when the user clicks on it then a page of this kind ↓ opens up

image

@SamarthUrane is currently working on admin panel and he is making very similar thing there...so i also assigned this issue to him.
you have implemented the functionality now @SamarthUrane  will do the required changes....if he asks for any help...you can hel him.

**Comment by Tomkndn** [comment]
> can you show the household common entries and just below them should be entries of associated family members that were entered at that time...and after that result&chart is shown
> 
> Screenshot 2024-06-06 012817
> 
> OR
> 
>  Along with total Carbon Footprint, Chart, Recommendation....
> 
> and business form is also saving the entries in the DB...make for that too.

Earlier you mentioned it it was okay,  just add those entries and then you edited it.
That's not a good practice and now you decided to change the design without informing me.

**Comment by adarsh-singh01** [comment]
> > can you show the household common entries and just below them should be entries of associated family members that were entered at that time...and after that result&chart is shown
> > 
> > Screenshot 2024-06-06 012817
> > 
> > OR
> > 
> >  Along with total Carbon Footprint, Chart, Recommendation....
> > 
> > and business form is also saving the entries in the DB...make for that too.
> 
> Earlier you mentioned it it was okay,  just add those entries and then you edited it.
> That's not a good practice and now you decided to change the design without informing me.

Calm down brother, I didn't plan to change the design but i REALISED that it looks cluttered and then Samarth sent me the design that he has chosen to make the admin panel... Then I added him here also, so that the website looks consistent . 

Btw,I didn't mean to hurt your feelings

I will merge your PR .

**Comment by adarsh-singh01** [comment]
Kindly implement for business also

**Comment by Tomkndn** [comment]
But see man, This was not good at all.

**Comment by Tomkndn** [comment]
> Kindly implement for business also

Below attached my progress

https://github.com/adarsh-singh01/PrithWe/assets/105445488/b7a9860a-21ef-46a4-a8f1-4acb27ca3d87

 
No worries, I was delayed in responding because of my end-semester exams.

**Comment by adarsh-singh01** [comment]
Have you updated your PR code as when i am testing it locally it is not showing family member entries.

**Comment by Tomkndn** [comment]
Updated my PR.

**Comment by Tomkndn** [comment]
> Have you updated your PR code as when i am testing it locally it is not showing family member entries,and it is not responsive

A humble request for responsiveness please create a another issue beacuse implementing history page for both form was a big task.
Please!!!

**Comment by adarsh-singh01** [comment]
> > Have you updated your PR code as when i am testing it locally it is not showing family member entries,and it is not responsive
> 
> A humble request for responsiveness please create a another issue beacuse implementing history page for both form was a big task. Please!!!

ok bro,no problem

**Comment by Tomkndn** [comment]
Wait something got clashed.

**Comment by Tomkndn** [comment]
Done, I have also made a calulator file where all calculating formulas are present such that the formula can be use by just importing to it.

**Review by adarsh-singh01 — APPROVED** [review]

**Comment by adarsh-singh01** [comment]
is this complete from your end ?...should i merge this now?

**Comment by adarsh-singh01** [comment]
Merged... Thanks for your contribution

**Pull request merged**
