### PR TITLE
Fix in UI of User Details (Admin Panel)

### PR DESCRIPTION
**Pull request by PratikMane0112**
Fix issue #115 

Screenshot 2024-06-12 000734

Screenshot 2024-06-12 000754
Screenshot 2024-06-12 000804
Screenshot 2024-06-12 000816

### CODE REVIEW

**Comment by adarsh-singh01** [comment]
Everything is fine but

**Comment by adarsh-singh01** [comment]
Only update this thing... I will merge your PR...

**Comment by PratikMane0112** [comment]
ok

**Comment by PratikMane0112** [comment]
> i think you misunderstood "total carbon footprint" as merely a heading....but it is this thing
> 
> image

Is it Ok if I store this directly in database after calculating first time So we don't have to calculate that multiple times we can directly fetch it when we want

**Comment by adarsh-singh01** [comment]
> > i think you misunderstood "total carbon footprint" as merely a heading....but it is this thing
> > image
> 
> Is it Ok if I store this directly in database after calculating first time So we don't have to calculate that multiple times we can directly fetch it when we want

I think calculating each time will be good ...as there is thing called "emission factors" which is used in formula and they change over time...so if we save the "Total CF" it would show the old calculated value and not the new one based on new emission factor.

**Comment by adarsh-singh01** [comment]
the guy who previously made the History has implemented that feature...you can take inspiration from there if u want

**Comment by PratikMane0112** [comment]
Ok, I will do it tomorrow.

**Comment by adarsh-singh01** [comment]
> Ok, I will do it tomorrow.
okay no problem

**Comment by PratikMane0112** [comment]
Screenshot 2024-06-12 111130
Screenshot 2024-06-12 111140
Screenshot 2024-06-12 111150

**Comment by adarsh-singh01** [comment]
Merged!

**Pull request merged**
