### PR TITLE
Added CONTRIBUTION.md

### LINKED ISSUE #2: Add Contribution.md
Hey @adarsh-singh01  ,
To streamline the contribution process and make it easier for new contributors to get involved, it's important to have clear and detailed contribution guidelines. A CONTRIBUTING.md file outlines the steps and best practices for contributing to the project, ensuring consistency and high-quality contributions.
Please assign me this issue

### PR DESCRIPTION
**Pull request by Santhosh-Siddhardha**
Added Ways to Contribute Section
Added Development Workflow section
Added Issue Report Process Section
Added Help regarding some basics section
Added Pull Request process
Added Community Guidelines
Added Documentation Section
Added Code reviews Section
Added Feature request Section
Added Spread the word Section

Closes #2

### CODE REVIEW

**Review by adarsh-singh01 — CHANGES_REQUESTED** [review]
Remove any personal social accounts from this file. 

Example:
If any issue contact me on tusharamd#5800 on discord

**Comment by Santhosh-Siddhardha** [comment]
@adarsh-singh01 Made changes, Have a look

**Comment by Santhosh-Siddhardha** [comment]
@adarsh-singh01 Please add gssoc and level labels for the PR

**Comment by Santhosh-Siddhardha** [comment]
@adarsh-singh01 Please assign this PR to me and add gssoc and level labels

**Pull request merged**
