### PR TITLE
After opening dialog box by click on hamburger that icon should be close icon #76

### PR DESCRIPTION
**Pull request by kapilG0**
After opening dialog box by click on hamburger that icon should be close icon #76

### CODE REVIEW

**Comment by adarsh-singh01** [comment]
> After opening dialog box by click on hamburger that icon should be close icon #76

Send a short video of this functionality

**Comment by kapilG0** [comment]
> > After opening dialog box by click on hamburger that icon should be close icon #76
> 
> Send a short video of this functionality

Hello @adarsh-singh01 . please check 

https://github.com/adarsh-singh01/PrithWe/assets/59639410/da2a8c3f-6115-4acf-a0b3-40f256003d06

**Comment by kapilG0** [comment]
Hello @adarsh-singh01 please review the above video if any changes required please let me know thanks

**Comment by adarsh-singh01** [comment]
Hey Kapil, currently I am caught up in some other work... Will merge your PR tomorrow

**Comment by kapilG0** [comment]
> Hey Kapil, currently I am caught up in some other work... Will merge your PR tomorrow

Ok

**Comment by adarsh-singh01** [comment]
Please make the Cross and hamburger icon a little bigger like the size it was before and

Fix this bug : the cross icon does not turn into a hamburger once it is closed...

**Comment by kapilG0** [comment]
> 
> 
> Please make the Cross and hamburger icon a little bigger like the size it was before and
> 
> Fix this bug : the cross icon does not turn into a hamburger once it is closed...

i have raised pr #120 and that is not bug the thing is if dialog close than hamburger will come if after click on hamburger dialog opens then cross icon comes

**Comment by kapilG0** [comment]
Hello @adarsh-singh01 please check pr https://github.com/adarsh-singh01/PrithWe/pull/131. Thank you

**Pull request merged**
