### PR TITLE
Toggle password

### PR DESCRIPTION
**Pull request by kushalkumar1362**
### Summary:
This pull request introduces the react-icons library to the project and integrates the eye icon for toggling password visibility in both the login and sign-up forms.

### Changes:

  - Added the react-icons library to the project dependencies.
  - Imported the eye icon from react-icons to be used in the password input fields.
  - Implemented functionality to toggle the visibility of the password in the login form.
  - Implemented functionality to toggle the visibility of the password in the sign-up form.

### Screenshots:
image

image

### Additional Notes:

  - This change enhances the user experience by allowing users to easily see and verify their password entries.
  - No breaking changes introduced.

### CODE REVIEW

**Comment by kushalkumar1362** [comment]
#27

**Comment by adarsh-singh01** [comment]
Hey kushal! There are some merge conflicts happening because some changes were made in the original repo after you had forked the repo... Can you fix this and then send a PR?

**Comment by kushalkumar1362** [comment]
Now please merge this before doing any change

**Comment by adarsh-singh01** [comment]
Merged!

**Pull request merged**
