### PR TITLE
Added User Details in admin Section

### PR DESCRIPTION
**Pull request by SamarthUrane**
Solved Issue No. #69  under GSSOC'24. In admin Section admin can see User Details on clicking on the specific User.
Screenshot 2024-06-05 230404

image

image

### CODE REVIEW

**Comment by SamarthUrane** [comment]
Please Merge this or update me if any changes are required

**Review by adarsh-singh01 — APPROVED** [review]

**Comment by adarsh-singh01** [comment]
hey i noticed this after merge...that household common and family members are not shown collectively...can you show the household common entries and just below them should be entries of associated family members that were entered at that time...

a `div` should have common entries and its `sub-divs` have family members entry associated with it

**Comment by adarsh-singh01** [comment]
image
image
image
 can you make it like this ?

**Comment by SamarthUrane** [comment]
Is it Ok If I do this tomorrow?

**Comment by SamarthUrane** [comment]
I think we should show the dates when the calculation is made. This will be good experience for admin and user to see history and dates are available

**Comment by SamarthUrane** [comment]
I will create new Issue for updating UI for user details and adding dates

**Comment by adarsh-singh01** [comment]
Okay

**Pull request merged**
