### PR TITLE
"Added Two Way Communication"

### PR DESCRIPTION
**Pull request by falgun143**
Solves #93 .

Below videos shows the changes .

https://github.com/adarsh-singh01/PrithWe/assets/105922142/ae933d82-2593-4fae-8f63-64955f271067

https://github.com/adarsh-singh01/PrithWe/assets/105922142/9b1a2df9-e27f-4c9d-8dc3-c16708bf8d1a
@adarsh-singh01 Please review.

### CODE REVIEW

**Comment by falgun143** [comment]
@adarsh-singh01  Have you gone through the pr? ,Please let me know if there is anything to update

**Comment by adarsh-singh01** [comment]
Actually, I had an exam today... Will review your PR today

**Comment by adarsh-singh01** [comment]
hey @falgun143 this error is coming while i am deploying it ....because of this line (

const getHtmlTemplate = (otp) => {

  const templatePath = path.resolve(__dirname, "EmailTemplates", "SendOtp.html");

  const templatePath = path.resolve(__dirname, "EmailTemplate", "emailTemplate.html");

  let template = fs.readFileSync(templatePath, "utf8");
  return template.replace("{{otp}}", otp);
};)
image

**Comment by adarsh-singh01** [comment]
Hello @falgun143 ...can you please tell me what should I do to remove the error... Without altering any other feature

**Pull request merged**
