### PR TITLE
Added Custom Scrollbar

### LINKED ISSUE #44: [Feature] Add Custom Scrollbar
**Description:**
The platform currently lacks the functionality of theme-matching scrollbar which are pivotal for improving user comfort and navigation fluidity. By integrating this feature, I aim to provide users with a smoother and more personalized browsing experience.

I have implemented this feature multiple times in open source as well as personal projects, so please assign this issue to me under GSSoC'24.

### PR DESCRIPTION
**Pull request by SwanandD121**
Scrollbar with same theme added to enhance the UI.

image

Fixes #44

### CODE REVIEW

**Comment by adarsh-singh01** [comment]
Merged!

**Comment by SwanandD121** [comment]
> Merged!

Hey, thanks for merging.

Just one thing, you labelled the issue (#44) for this pull request as **Level 2** and in the PR, you labelled it as **Level 1**. If you could label the PR as **Level 2** as well, it would be great.

**Comment by adarsh-singh01** [comment]
hey there is one issue with scrollbar when i am hovering over it...it gives this effect
Screenshot (1378)

**Comment by SwanandD121** [comment]
> hey there is one issue with scrollbar when i am hovering over it...it gives this effect Screenshot (1378)

Hey,
Maybe this issue came up later with some other PR because when I tested it after you merged my PR, it was working fine.
Still I'll check the code once and get back to you with a solution asap.

**Pull request merged**
