### PR TITLE
Fixed the force reload issue and improved the toastify notification

### PR DESCRIPTION
**Pull request by Tomkndn**
Fixes: #7 
Description: 
1. Login and logout was forcibly reloading the website which results in bad experince to the user. I have implemented the same it will just redirect to the desired routes for both login and logout function without reloading which increases the User Experience.
2. I have improved the toastify notification as the ToastContainer and the respective css is written in all the required components. My approach to place it in the parent container i.e (App.jsx) such that no need of writing the toast container to all the components for rendering unneccesarily.

### CODE REVIEW

**Comment by adarsh-singh01** [comment]
Error is coming during merge

**Comment by Tomkndn** [comment]
Please review again.

**Comment by adarsh-singh01** [comment]
> Please review again.

Yes Conflicts are resolved now...Some changes were made in the header file and a Markdown file after you had forked and cloned it thats why that was coming...

**Comment by adarsh-singh01** [comment]
Will merge in few hours

**Comment by Tomkndn** [comment]
I got it after some time, Thanks btw.
Also dont forget to label the PR under gssoc contribution.

**Comment by Tomkndn** [comment]
I am waiting for this PR to be merged.
So that I will start working on the other issue which was assigned to me.

**Comment by adarsh-singh01** [comment]
> I am waiting for this PR to be merged.
> So that I will start working on the other issue which was assigned to me.

Hey Kundan, Currently I was waiting for my mentor to review the enhancement labeled PRs, but currently she is busy, so I will merge your PR shortly after reviewing.

**Comment by adarsh-singh01** [comment]
Can you please share a short video of you logging in and going to the calculator page and then logging out.

**Comment by Tomkndn** [comment]
Below attached the proof of the solution -

https://github.com/adarsh-singh01/PrithWe/assets/105445488/29a993d1-e3a4-4663-9930-bf5b1f0959d9

**Comment by adarsh-singh01** [comment]
Merged!

**Comment by Tomkndn** [comment]
Thanks, Now I will start worknig on the other issue.

**Pull request merged**
