### PR TITLE
add dark/light mode toggle btn

### PR DESCRIPTION
**Pull request by prachita0504**
problem number : #3

### CODE REVIEW

**Comment by adarsh-singh01** [comment]
Can you send a short video of this functionality

**Comment by prachita0504** [comment]
Uploading Recording 2024-06-01 214331.mp4…

**Comment by adarsh-singh01** [comment]
> 
> Uploading Recording 2024-06-01 214331.mp4…
> 
> 

I think you should have waited for a few seconds...you sent it while it was uploading

**Comment by prachita0504** [comment]
https://github.com/adarsh-singh01/PrithWe/assets/139040702/cf1b3aad-dd37-49bc-b753-290b05a9d6fd

**Comment by adarsh-singh01** [comment]
Hey Prachita, the functionality looks Good but the colors are looking little odd...can you fix this

 I think you should learn little about color theory in UI/UX, take inpiration from famous websites and even Tailwind tailwind have a doc on it https://tailwindcss.com/docs/dark-mode ...
please see this.

**Comment by adarsh-singh01** [comment]
If you need any assistance...then tell me... i can add some contributors in this PR .

**Comment by prachita0504** [comment]
no need i can do it by today

**Comment by prachita0504** [comment]
Screenshot 2024-06-02 105550
is this better

**Comment by adarsh-singh01** [comment]
yes,it is better from previous one.

**Comment by adarsh-singh01** [comment]
Hey Prachita,many changes have came to the original,  the repo you had forked should have become few commits behind. So, it is giving an error branch conflict error. 

Try resolving the conflicts in the VS Code , it provides the merge editor which is easy to use.

**Comment by prachita0504** [comment]
i don't understand

**Comment by adarsh-singh01** [comment]
> i don't understand 

Okay... I did it

**Comment by adarsh-singh01** [comment]
merged ! ... thanks for your contribution

**Comment by prachita0504** [comment]
thank you!

**Pull request merged**
